language: php
php:
  - 5.3
  - 5.4

services:
  - mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev


script: if [ $TRAVIS_PHP_VERSION = 5.3 ]; then ./bin/phpunit --coverage-text --exclude-group 5.4; else ./bin/phpunit --coverage-text; fi

notifications:
  email: false
