language: php
php:
  - 5.3
  - 5.4

services:
  - mongodb

env:
  - MONGO_VERSION=1.3.4

before_script:
   - pecl -q install mongo-${MONGO_VERSION} && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: phpunit --coverage-text

notifications:
  email: false